### ISSUE TITLE
Logging System

### ISSUE THREAD

**Issue by vlChris** [Vocalogic/logic#155]
I want to create a new logging system for all objects in Logic. It should be easy to use and support an audit log, and level. 

So, off the cuff, I want to have an log level setting. Each entry being set will have a log level, lowest being debug, then info, error, etc.

Using this should be super easy since it's going to be mass used across the platform, and I don't want people to have to dig around and figure out how to use this command. 

We will refactor LoLog to accept a signature like. 
```php
_log($invoice, "Sent invoice to so and so", LogType::INFO);
```
All inference will be done inside the logger with a few "instanceof" cases that will set the database entries for like account_id if applicable, the type (in this case Invoice) and the id (off the $invoice->id)

Info log type will be default, so we don't even need to specify LogType at the end there unless it's an error or a debug.

We then will be able to go into an account, invoice, lead, quote whatever, and see everything related to it. Should there be a sync issue to quickbooks? We would then tag that to the invoice, log type of error and the message be the error and  the exception output in details.

An error could look like: 
```php
_log($invoice, "Error Syncing Invoice to Quickbooks", LogType::ERROR, $e->getMessage());
```
I mean obviously we'd probably encode it if it's json or whatever, but I think the idea is clear.

**Comment by vlChris** [comment]
Furthermore, I don't want to do just straight model auditing. I don't believe it's that important other than an account was updated by a particular user on a timestamp. We may look at a raw auditor later, but for now I want to manually write these log entries on the controllers and operations that need to log things for info, warn, debug, whatever.

**Comment by sodu-parisev** [comment]
Hi, do you need help with implementing this feature ? If yes what is the deadline until should be done ?

**Comment by vlChris** [comment]
Of course! No time limit really.. if you want to chat about some ideas on implementing or have questions hit me up on the discord off the readme

**Comment by vlChris** [comment]
Some thoughts on this. 

* We create a LogSeverity enum - default cast to int. Its definition would be like

```php
enum LogSeverity
{
 case None = 0;
 case Low = 1;
 case High = 2;
 case Debug = 3;

 public function getHuman(): string
 { 
    return match($this)
   {
      self::None => 'No Logging', 
      self::Info => "Information/Errors Only", // etc
   };
 }

}
```
This way when we create a setting in the SettingSeeder that says "Specify Log Level" it will be selectable. We can create a static function in here called getSelectable() that iterates over the cases and has their human readable name for a select box. Many of the other enums do this. 

Our new table structure will be pretty simple. 

**id**
**timestamps**
**account_id** INT NULLABLE (any object given that has an account_id we should set here so when in an account we can see all log entries for that account.
**type** STRING - This will be the class type. So if we send in an $invoice then the type would pull the model class name "Invoice"
**type_id** INT - This is the id field of the object given. So with type and type_id we can infer Invoice::find(type_id)
**log_level** INT - This is the enum from log severity
**log** STRING - This will be the main message, and really the only thing required for sending a log entry. 
**detail** TEXT NULLABLE - If we need to add additional data (like an exception trace) we can put that here but not required. 

I think that will get us started. 

Then we will create (or replace) _log() in helpers.php that instantiates a new LogEngine class.. This class will take in the object, the log, and the log level associated.

The class will then determine if it should save the log entry based on the setting provided. This is why we have them as int in the enum, so we can compare the integer value.. if the setting < log level given then we just ignore the entry and move on. 

To fill account_id.. Look at each object and see if it has an account_id off of it, if it does store that in the account_id field.

**Comment by sodu-parisev** [comment]
Also as we discussed it is good add `user_id` field, that will say who initiated an event.

**Comment by vlChris** [comment]
Core of this is completed. Additional issues for rendering views and more coming
