### ISSUE TITLE
Create a route for logs

### ISSUE THREAD

**Issue by sodu-parisev** [Vocalogic/logic#178]
As we discussed we need a route like `/admin/logs/{model}/{id}` to display log messages. Where `model` corresponds to a model class, for example `invoice` corresponds to class `App\Models\Invoice`.

**Comment by vlChris** [comment]
Testing contributors adding @sodu-parisev to @all-contributors

**Comment by vlChris** [comment]
@all-contributors add @sodu-parisev for code
